name: tap-looker
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39hbda83bc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libopenblas=0.3.30=hf2bb037_2
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - ncurses=6.5=hee39554_0
  - numexpr=2.10.1=py39h5d9532f_0
  - numpy=2.0.1=py39h3b2db8e_1
  - numpy-base=2.0.1=py39ha9811e2_1
  - openssl=3.0.18=h9b4081a_0
  - pandas=2.3.3=py39hc6ded6b_0
  - pip=25.3=pyhc872135_0
  - python=3.9.25=he39995d_1
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py39hca03da5_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py39hca03da5_0
  - six=1.17.0=py39hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - astroid==3.3.11
      - backoff==1.10.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - ciso8601==2.3.3
      - dill==0.4.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - isort==6.1.0
      - jsonschema==2.6.0
      - mccabe==0.7.0
      - platformdirs==4.4.0
      - pylint==3.3.9
      - requests==2.32.5
      - simplejson==3.11.1
      - singer-python==5.14.3
      - tomli==2.4.0
      - tomlkit==0.14.0
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - zipp==3.23.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/tap-looker
